import streamlit as st
import pandas as pd
from fpdf import FPDF


def safe_read_csv(uploaded_file, required_columns):
    """Reads a CSV safely. Shows a friendly message instead of a raw error
    if the file is invalid or missing required columns."""
    try:
        df = pd.read_csv(uploaded_file)
    except Exception:
        st.error("⚠️ This file couldn't be read. Please upload a valid CSV file.")
        return None

    missing = [c for c in required_columns if c not in df.columns]
    if missing:
        st.error(f"⚠️ This file is missing required column(s): {', '.join(missing)}. "
                  f"Please check the format and try again.")
        return None
    return df


def apply_custom_style():
    """Injects custom CSS for a classy dark background and card styling."""
    st.markdown("""
        <style>
        .stApp {
            background: linear-gradient(135deg, #0f1729 0%, #1a2540 55%, #0f1729 100%);
        }
        [data-testid="stSidebar"] {
            background-color: #131c31;
        }
        [data-testid="stMetric"] {
            background-color: rgba(255, 255, 255, 0.04);
            border: 1px solid rgba(255, 255, 255, 0.08);
            border-radius: 10px;
            padding: 12px;
        }
        h1, h2, h3 {
            color: #e8ecf5;
        }
        </style>
    """, unsafe_allow_html=True)


def _break_long_words(text, max_len=15):
    words = text.split(" ")
    fixed_words = []
    for word in words:
        if len(word) > max_len:
            chunks = [word[i:i + max_len] for i in range(0, len(word), max_len)]
            fixed_words.append(" ".join(chunks))
        else:
            fixed_words.append(word)
    return " ".join(fixed_words)


def generate_pdf_report(title, sections):
    """sections = list of (heading, list_of_text_lines) tuples."""
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    usable_width = pdf.w - pdf.l_margin - pdf.r_margin

    pdf.set_font("Helvetica", "B", 18)
    pdf.set_x(pdf.l_margin)
    pdf.cell(usable_width, 12, title, new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("Helvetica", "", 10)
    pdf.set_x(pdf.l_margin)
    pdf.cell(usable_width, 8, "Generated by PulseMetrics", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    for heading, lines in sections:
        pdf.set_font("Helvetica", "B", 13)
        pdf.set_x(pdf.l_margin)
        pdf.cell(usable_width, 10, heading, new_x="LMARGIN", new_y="NEXT")

        pdf.set_font("Helvetica", "", 11)
        for line in lines:
            safe_line = str(line).encode("latin-1", "replace").decode("latin-1")
            safe_line = _break_long_words(safe_line)
            if safe_line.strip() == "":
                safe_line = " "
            pdf.set_x(pdf.l_margin)
            pdf.multi_cell(usable_width, 7, safe_line)
        pdf.ln(3)

    return bytes(pdf.output(dest="S"))